[package]
name = "sm-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sm-entity = { path = "../entity" }
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = { workspace = true }